#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Android kernel building script
# Copyright (C) 2018 Raphiel Rollerscaperers (raphielscape)
# Copyright (C) 2018 Rama Bondan Prakoso (rama982)
# Copyright (C) 2021 Salman Wahib (sxlmnwb)

# Clear on screen
clear

# Removing dir out and log
rm -rf out
rm -f testing.log

# Clean before build
make clean && make mrproper

# Main environtment
KERNEL_DIR=$PWD
KERN_IMG=$KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb
ZIP_DIR=$KERNEL_DIR/AnyKernel3
CONFIG=xBoreUp-onclite_defconfig
CROSS_COMPILE="aarch64-linux-gnu-"
CROSS_COMPILE_ARM32="arm-linux-gnueabi-"
PATH=:"${KERNEL_DIR}/LLVM-Prebuilts/bin:${PATH}:${KERNEL_DIR}/64/bin:${PATH}:${KERNEL_DIR}/32/bin:${PATH}"

# Export
export KBUILD_BUILD_USER=sxlmnwb
export KBUILD_BUILD_HOST=sxlzptprjkt
export ARCH=arm64
export CROSS_COMPILE
export CROSS_COMPILE_ARM32

# Building start
START=$(date +%s)
make O=out $CONFIG
make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
CLANG_TRIPLE=aarch64-linux-gnu- \
CROSS_COMPILE=aarch64-linux-android-

if ! [ -a $KERN_IMG ]; then
    echo "BUILDING ERROR !"
    exit 1
fi

cd $ZIP_DIR
make clean &>/dev/null
cd ..

# For MIUI build
# Credit Adek Maulana <adek@techdro.id>
OUTDIR="$KERNEL_DIR/out/"
VENDOR_MODULEDIR="$KERNEL_DIR/AnyKernel3/modules/vendor/lib/modules"
STRIP="$KERNEL_DIR/64/bin/$(echo "$(find "$KERNEL_DIR/64/bin" -type f -name "aarch64-*-gcc")" | awk -F '/' '{print $NF}' |\
            sed -e 's/gcc/strip/')"
for MODULES in $(find "${OUTDIR}" -name '*.ko'); do
    "${STRIP}" --strip-unneeded --strip-debug "${MODULES}"
    "${OUTDIR}"/scripts/sign-file sha512 \
            "${OUTDIR}/certs/signing_key.pem" \
            "${OUTDIR}/certs/signing_key.x509" \
            "${MODULES}"
    find "${OUTDIR}" -name '*.ko' -exec cp {} "${VENDOR_MODULEDIR}" \;
done
echo -e "\n DONE MOVING MODULES !"

# Zipping kernel to AnyKernel3
cd $ZIP_DIR
cp $KERN_IMG zImage
make normal &>/dev/null
echo "Flashable zip generated under $ZIP_DIR."
echo "Please wait sending ZIP kernel to telegram ..."

# End to build
END=$(date -u +%s)
DURATION=$(( END - START ))

# Moving kernel to dir AnyKernel3
cd $KERNEL_DIR/AnyKernel3
mv "$(echo xBoreUp-AOSP-*.zip)" "$KERNEL_DIR"
cd $KERNEL_DIR

# Add new variable
KBUILD_BUILD_TIMESTAMP=$(date)
export KBUILD_BUILD_TIMESTAMP
CPU=$(lscpu | sed -nr '/Model name/ s/.*:\s*(.*) @ .*/\1/p')
HEAD_COMMIT="$(git rev-parse HEAD)"
NAME="sxlmnwb"
GITHUB_URL="https://github.com/sxlmnwb/msm-4.9/commits/"
COMMIT=$(git log --pretty=format:'%h: %s' -1)

# Sending to telegram
./telegram -f "$(echo -e xBoreUp-AOSP-*.zip)" "$(echo $'\n\n' ---BUILDING--- $'\n' $COMMIT $'\n\n' COMMIT URL : $'\n' ${GITHUB_URL}${HEAD_COMMIT} $'\n\n' DATE : $'\n' $KBUILD_BUILD_TIMESTAMP $'\n\n' BUILD USING : $'\n' $CPU $'\n\n' AUTHOR : $'\n' $NAME $'\n\n' DURATION : $'\n' $DURATION Seconds $'\n' ---COMPLETE--- )"
rm "$(echo xBoreUp-AOSP-*.zip)"
echo -e "\n DONE SENDING TO TELEGRAM !"

# Banner
echo "Finish Building Kernel"

# Build end
